apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo-cd-setup
  namespace: argocd
spec:
  description: Project for Argo CD setup
  sourceRepos:
    - https://github.com/rogeriorocha/gitops-k8s.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
