env: dev
argo:
  multiCluster: false
apps:
  # Service Mesh
  - name: istio
    enabled: true
    namespace: istio-system
    loadPath: app/service-mesh/istio
    ignoreDifferences:
      # Ignore caBundle diff due to runtime updates to the config
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/0/failurePolicy
      - group: admissionregistration.k8s.io
        kind: ValidatingWebhookConfiguration
        jsonPointers:
          - /webhooks/0/clientConfig/caBundle
          - /webhooks/0/failurePolicy

# argoCD config
# Metadata
metadata:
  finalizers:
    enabled: true
# Overrides
spec:
  source:
    gitRepoUrl: https://github.com/rogeriorocha/gitops-k8s.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune:
        # Specifies if resources should be pruned during auto-syncing
        # ( false by default ).
        enabled: true
      selfHeal:
        # Specifies if partial app sync should be executed when resources
        # are changed only in target Kubernetes cluster and no git change
        # detected ( false by default ).
        enabled: true
#